version: '3.8'

services:
  wsgi:
    build: '.'
    container_name: manga_crawler_wsgi
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      - APP_NAME=MangaCrawler